aws:
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
    ansible_connection: ssh
    ansible_ssh_user: centos
    ansible_become: true

    zookeeper_tls_enabled: true
    zookeeper_client_authentication: mtls
    zookeeper_server_authentication: mtls

    kafka_container_overrides:
      environment:
        DOMS_ENV_VAR: whatever

  children:
    zookeeper:
    kafka:
    schema_registry:

zookeeper:
  hosts:
    zookeeper1:
      hostname: ip-172-31-47-105.us-west-2.compute.internal
      ansible_host: ec2-18-236-90-153.us-west-2.compute.amazonaws.com
    zookeeper2:
      hostname: ip-172-31-43-87.us-west-2.compute.internal
      ansible_host: ec2-52-11-75-142.us-west-2.compute.amazonaws.com
    zookeeper3:
      hostname: ip-172-31-37-171.us-west-2.compute.internal
      ansible_host: ec2-54-184-73-238.us-west-2.compute.amazonaws.com

kafka:
  hosts:
    kafka1:
      hostname: ip-172-31-47-105.us-west-2.compute.internal
      ansible_host: ec2-18-236-90-153.us-west-2.compute.amazonaws.com
    kafka2:
      hostname: ip-172-31-43-87.us-west-2.compute.internal
      ansible_host: ec2-52-11-75-142.us-west-2.compute.amazonaws.com
    kafka3:
      hostname: ip-172-31-37-171.us-west-2.compute.internal
      ansible_host: ec2-54-184-73-238.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    schema_registry1:
      hostname: ip-172-31-35-250.us-west-2.compute.internal
      ansible_host: ec2-54-187-238-13.us-west-2.compute.amazonaws.com
