---
- hosts: zookeeper
  gather_facts: false
  tasks:
    - name: Create SSL Files
      import_role:
        name: ssl
      vars:
        component_name: zookeeper
      delegate_to: localhost

- hosts: kafka
  gather_facts: false
  tasks:
    - name: Create SSL Files
      import_role:
        name: ssl
      vars:
        component_name: kafka
      delegate_to: localhost
