---
- hosts: zookeeper:kafka_broker:schema_registry:kafka_connect:ksql:control_center:kafka_rest
  gather_facts: false
  tasks:
    - name: Create Certificate Authority
      import_role:
        name: ssl
        tasks_from: ca.yml
      run_once: true
      delegate_to: localhost
