---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Create Certificate Authority
      import_role:
        name: ssl
        tasks_from: ca.yml
      run_once: true
      delegate_to: localhost

    - name: Get FQDN of Host
      setup:
        filter: ansible_fqdn
        gather_subset:
          - '!all'

    - name: Set hostname variables on each host
      set_fact:
        hostname: "{{ansible_fqdn}}"

    - name: Create SSL Files
      import_role:
        name: ssl
      vars:
        component_name: "{{inventory_hostname}}"
      delegate_to: localhost

    - name: Create Docker Compose Files
      import_role:
        name: docker_compose
        tasks_from: component_artifacts.yml

- hosts: zookeeper
  gather_facts: false
  tasks:
    - name: Deploy Docker Compose Files
      import_role:
        name: docker_compose
