---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install Docker Role
      shell: ansible-galaxy install geerlingguy.docker
      register: output
      changed_when: "'is already installed' not in output.stderr"

    # - name: Install Docker Role
    #   shell: ansible-galaxy collection install community.general

- name: Prepare
  hosts: all
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ansible_user}}"
      become: yes
