---
- name: Create Directory for SSL Files
  file:
    path: "{{component_output_dir}}"
    state: directory

- name: Create Truststore and Import the CA Cert
  shell: |
    keytool -noprompt -keystore {{truststore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{truststore_storepass}} \
      -keypass {{truststore_storepass}}
  args:
    # Assuming the truststore is correct if exists
    creates: "{{truststore_path}}"

- name: Create openssl Config for SAN
  template:
    src: openssl-san.cnf.j2
    dest: "{{component_output_dir}}/openssl-san.cnf"

- name: Create Keystore, Sign Certificate and Import Signed Cert and CA
  shell: |
    # Create Keystore
    keytool -genkey -noprompt \
      -storetype pkcs12 \
      -keyalg {{ssl_key_algorithm}} -keysize {{ssl_key_size}} \
      -alias {{hostname}} \
      -dname "CN={{component_name}},OU=TEST,O=CONFLUENT,L=PaloAlto,S=Ca,C=US" \
      -ext "SAN=dns:{{hostname}}" \
      -keystore {{keystore_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

    # Create Certificate Signing Request
    keytool -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias {{hostname}} \
      -certreq -file {{component_output_dir}}/client.csr \
      -ext "SAN=dns:{{hostname}}" \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

    # Sign CSR with the Certificate Authority
    openssl x509 -req -CA {{ca_cert_path}} \
      -CAkey {{ca_key_path}} \
      -in {{component_output_dir}}/client.csr \
      -out {{cert_path}} \
      -days {{keystore_expiration_days}} -CAcreateserial \
      -passin pass:{{ca_password}} \
      -extfile {{component_output_dir}}/openssl-san.cnf \
      -extensions v3_req

    # Import the CA cert into the Keystore
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias CARoot \
      -import -file {{ca_cert_path}} \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}

    # Import the Signed Host Cert into the Keystore
    keytool -noprompt -keystore {{keystore_path}} \
      -storetype pkcs12 \
      -alias {{hostname}} \
      -import -file {{cert_path}} \
      -ext "SAN=dns:{{hostname}}" \
      -storepass {{keystore_storepass}} \
      -keypass {{keystore_storepass}}
  args:
    # Assuming the keystore is correct if exists
    creates: "{{keystore_path}}"

- name: Export Key from Keystore
  shell: |
    openssl pkcs12 \
        -in {{keystore_path}} \
        -passin pass:{{keystore_storepass}} \
        -nodes -nocerts \
        -out {{key_path}}
  args:
    # Assuming the truststore is correct if exists
    creates: "{{key_path}}"

- name: Delete unnecessary SSL Files
  file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{component_output_dir}}/client.csr"
    - "{{component_output_dir}}/openssl-san.cnf"
    - "{{ca_output_dir}}/ca.srl"
