---
- name: Destroy Containers
  shell: |
    /usr/local/bin/docker-compose rm --stop --force {{inventory_hostname}}
  args:
    chdir: "{% if ansible_connection == 'local' %}{{playbook_dir}}/docker/{{ansible_host}}{% else %}/opt/confluent{{inventory_hostname}}{% endif %}"
  register: remove
  changed_when: "'No stopped containers' not in remove.stdout"
  failed_when: "'No stopped containers' not in remove.stdout and 'Going to remove {{inventory_hostname}}' not in remove.stdout"
